version: '3.2'
services:

  rabbitmq:
    image: rabbitmq:3-management
    container_name: 'rabbitmq'
    # Secreties these
    environment:
    - 'RABBITMQ_DEFAULT_PASS=guest'
    - 'RABBITMQ_DEFAULT_USER=guest'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - '~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/mnesia/'
    networks:
        - rabbitmq_network

  graphql:
    container_name: service.graphql
    build:
      dockerfile: Dockerfile.graphql.service
    ports:
      - 7000:5010
    networks:
      - rabbitmq_network
    depends_on:
      - rabbitmq
  
  user:
    container_name: service.user
    build:
      dockerfile: Dockerfile.user.service
    ports:
      - 8000:5000
    networks:
      - rabbitmq_network
    depends_on:
      - rabbitmq

  db:
    image: postgres:14.1-alpine
    restart: always
    # Secreties these
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data

volumes:
  db: 
    driver: local

networks:
  rabbitmq_network:
    driver: bridge