version: '3.2'
services:

  rabbitmq:
    image: rabbitmq:3-management
    container_name: 'rabbitmq'
    # Secreties these
    environment:
    - 'RABBITMQ_DEFAULT_PASS=guest'
    - 'RABBITMQ_DEFAULT_USER=guest'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - '~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/mnesia/'
    networks:
        - rabbitmq_network

  graphql:
    container_name: service.graphql
    build:
      dockerfile: Dockerfile.graphql.gateway
      context: .
    ports:
      - 7000:5010
    networks:
      - rabbitmq_network
    depends_on:
      - rabbitmq
  
  authentication:
    container_name: service.authentication
    build:
      dockerfile: Dockerfile.authentication
      context: .
      args:
        - PASSWORD=${DB_SERVICE_AUTHENTICATION_PASSWORD}
        - SECRET_TOKEN_KEY_VALUE=${JWT_SECRET_TOKEN_KEY_VALUE}
        - DOTNET_CLI_HOME=/tmp # Chatgpt said this is necessary to install ef globally :shrug:
    ports:
      - 8020:5020
    networks:
      - rabbitmq_network
      - db_network
    depends_on:
      - rabbitmq
      - db
      - graphql

  user:
    container_name: service.user
    build:
      dockerfile: Dockerfile.user
      context: .
      args:
        - PASSWORD=${DB_SERVICE_USER_PASSWORD}
        - DOTNET_CLI_HOME=/tmp # Chatgpt said this is necessary to install ef globally :shrug:
    ports:
      - 8000:5000
    networks:
      - rabbitmq_network
      - db_network
    depends_on:
      - rabbitmq
      - db
      - graphql
    
  db:
    container_name: server.postgres.pulu
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=postgres
      # - POSTGRES_PASSWORD=${DB_SERVICE_USER_PASSWORD}
      - POSTGRES_PASSWORD=${DB_SERVICE_USER_PASSWORD}
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
    networks:
      - db_network

volumes:
  db: 
    driver: local

networks:
  rabbitmq_network:
    driver: bridge
  db_network:
    driver: bridge