version: '3.2'
services:
  common:
    container_name: service.commons
    build: 
      dockerfile: Dockerfile.common.service
  graphql:
    depends_on:
      - common
    container_name: service.graphql
    build:
      dockerfile: Dockerfile.graphql.service
    ports:
      - 7000:5010
  user:
    depends_on:
      - common
    container_name: service.user
    build:
      dockerfile: Dockerfile.user.service
    ports:
      - 8000:5000
  rabbitmq:
    image: rabbitmq:3-management
    container_name: 'rabbitmq'
    environment:
    - 'RABBITMQ_DEFAULT_PASS=guest'
    - 'RABBITMQ_DEFAULT_USER=guest'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - '~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/mnesia/'
    networks:
        - rabbitmq_go_net

networks:
  rabbitmq_go_net:
    driver: bridge