version: "3.2"
services:
  common:
    container_name: service.commons
    build:
      context: ./Common
      dockerfile: ./Dockerfile
  graphql:
    container_name: service.graphql
    build:
      context: ./graphQL
      dockerfile: ./Dockerfile
    ports:
      - 7000:5010
  user:
    container_name: service.user
    build:
      context: ./User
      dockerfile: ./Dockerfile
    ports:
      - 8000:5000
  rabbitmq:
    image: rabbitmq:3-management
    container_name: 'rabbitmq'
    environment:
    - "RABBITMQ_DEFAULT_PASS=guest"
    - "RABBITMQ_DEFAULT_USER=guest"
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - '~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/mnesia/'
    networks:
        - rabbitmq_go_net

networks:
  rabbitmq_go_net:
    driver: bridge