name: Docker Compose push all images

on:
  workflow_run:
    workflows: ["CI build"]
    types:
      - completed

env:
  COMPOSE_LOCATION: server/services/docker-compose.yaml

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Login to Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PAT }}

      - name: Build and push Docker images
        env:
          DB_SERVICE_USER_PASSWORD: ${{ secrets.DB_SERVICE_USER_PASSWORD }}
        run: |
          docker-compose -f $COMPOSE_LOCATION build
          docker-compose -f $COMPOSE_LOCATION push
