
name: Docker Compose Up services

on:
  workflow_run:
    workflows: ["CI build"]
    types:
      - completed

env:
  COMPOSE_LOCATION: server/services/docker-compose.yaml 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Docker Compose Up
      with: 
        secrets:
          DB_SERVICE_USER_PASSWORD: ${{ secrets.DB_SERVICE_USER_PASSWORD }}
      run: docker compose -f $COMPOSE_LOCATION up -d

      

    #kill containers, for now
    - name: Docker Compose kill
      run: docker compose -f $COMPOSE_LOCATION down