name: CI build

on:
  push:
    branches: 
      - main

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
  
  build:
    needs: checkout
    strategy:
      matrix:
        service: ["server/services/User"]
    uses: "./.github/workflows/backend-services-build.yaml"
    with:
      directory: ${{ matrix.service }}
