name: CI build

on:
  push:
    branches: 
      - main

jobs:
  build:
    strategy:
      matrix:
        #add path for each service here
        service: ["server/services/User"]
    runs-on: ubuntu-latest
    steps:
    # We need this because GitHub needs to clone the branch to pipeline
      - name: Checkout
        uses: actions/checkout@v3

    - name: build .NET
      uses: "/IsssE/poppis-achiever/.github/workflows/backend-services-build.yaml@main"
      with:
        directory: ${{ matrix.service }}
  