name: CI build

on:
  push:
    branches: 
      - main

jobs:
  checkout:
    steps:
    # We need this because GitHub needs to clone the branch to pipeline
      - name: Checkout
        uses: actions/checkout@v3
  
  build:
    strategy:
      matrix:
        service: ["server/services/User"]
    runs-on: ubuntu-latest
    uses: "/IsssE/poppis-achiever/.github/workflows/backend-services-build.yaml@main"
    with:
      directory: ${{ matrix.service }}
