name: Build Services

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    # trying to build each service
    strategy:
      matrix:
        #add path for each service here
        service: ["server/services/User"]
    runs-on: ubuntu-latest
    steps:
    # We need this because GitHub needs to clone the branch to pipeline
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        uses: "./.github/workflows/backend-services-build.yaml"
        with:
          directory: ${{ matrix.service }}
   