name: CI build

on:
  push:
    branches: 
      - main

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
  
    # dotnet build and publish
      - name: Build with dotnet
        run: dotnet build --configuration Release
    